# Образ контйнера
FROM node
# Рабочая директория внутри контейнера
WORKDIR /app
# Копируем package.json и package-lock.json в рабочую директорию
COPY package*.json ./
# Установка зависимостей
RUN npm install
# Копируем все файлы
COPY . .
# Копируем папку dist
COPY ./dist ./dist
# Скрипт разработки
CMD ["npm", "run", "start:dev"]